### ISSUE TITLE
Using with FlowXO webhooks

### ISSUE THREAD

**Issue by vilbht** [ashubham/bot-context#1]
Hi there

Noob to building bots. This repo seems to solve an important problem with a lot of WYSIWYG bot tools. Do you know if it'd work with FlowXO. Added in 2 links to what seem like relevant custom code options.

> https://support.flowxo.com/article/22-webhooks
> https://support.flowxo.com/article/145-code

**Comment by ashubham** [comment]
@vilav `bot-context` can be used with any bot library/framework/platform.

From what it looks like on FlowXO is that they provide webhooks, to integrate with external systems. I would follow the same approach mentioned in the example of this project.

1. Setup a webserver(express or something). And create two endpoints for `recieve` and `send`.
2. You will define two outgoing webhooks from flowXO:
    - On receiving a message, send a request  to the `recieve` endpoint, here you will do context 
       matching.
    - When you send messages from flowXO, hit the `send` endpoint. Where you can set your
       contexts.

LMK if you have more questions.

**Comment by ashubham** [comment]
I have added an example for your case https://github.com/ashubham/bot-context/blob/master/examples/webhooks.js. Please reopen if that does not help.

**Comment by vilbht** [comment]
@ashubham thanks a ton for the sample code! Gonna try it out this week. Keep you posted on the progress!
